### ISSUE TITLE
Fix leaky CSS

### ISSUE THREAD

**Issue by phantomas1234** [DD-DeCaF/metabolica-ui-pathways#13]
Can't move https://github.com/biosustain/metabolica-ui/issues/35 to dd-decaf, so hear a duplicate. This needs to be fixed in all our modules actually.

**Comment by sgalkina** [comment]
done: fixed in all the modules

**Comment by matyasfodor** [comment]
https://github.com/DD-DeCaF/decaf-metabolica/commit/a32f293ed8ccd67674affc0c2aef75043a652bf6
https://github.com/DD-DeCaF/metabolica-ui-upload/commit/18dbfea78657767a09065edae0f3ab2f3a261e31
https://github.com/DD-DeCaF/metabolica-ui-map/commit/0945b64d60e5f15770997ee00ee4e6fda990eddc
