### ISSUE TITLE
As a user I want to see the first pathway predictions on the order of 1-5 seconds

### ISSUE THREAD

**Issue by sgalkina** [DD-DeCaF/metabolica-ui-pathways#2]
_From @phantomas1234 on March 1, 2017 11:12_

null

_Copied from original issue: DD-DeCaF/pathway-vis#35_

**Comment by sgalkina** [comment]
_From @phantomas1234 on March 1, 2017 11:13_

From D9.1:

2.2.4 Heterologous pathways
This module supposes to scout all possible pathways from a defined substrate to a defined product based on a universal biochemical reaction database and an organism-specific GSMM. We were unable to test this module due to very long run time.

**Comment by hredestig** [comment]
done: results on frontend doesn't take more than 5% more than local cameo
