### ISSUE TITLE
As a user I want to be able to focus on project specific data by relying on project specific modeling apps

### ISSUE THREAD

**Issue by sgalkina** [DD-DeCaF/metabolica-ui-pathways#3]
_From @phantomas1234 on March 8, 2017 11:16_

null

_Copied from original issue: DD-DeCaF/module-pathways#6_

**Comment by phantomas1234** [comment]
Issue moved to [DD-DeCaF/scrum #168](https://github.com/DD-DeCaF/scrum/issues/168) via [**ZenHub**](https://www.zenhub.com/)
